name: soft-deletable-bundle-CI
on:
  [push, pull_request]
jobs:
  build_php_7_4:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - uses: actions/checkout@v2
      - name: composer install
        run: composer install

  build_php_8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: composer install
        run: composer install

  check_code_php_7_4:
    runs-on: ubuntu-latest
    needs: [ build_php_7_4 ]
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - uses: actions/checkout@v2
      - name: composer install
        run: composer install

      - name: cs-check
        run: composer cs-check

      - name: phpstan
        run: composer phpstan

  check_code_php_8:
    runs-on: ubuntu-latest
    needs: [ build_php_8 ]
    steps:
      - uses: actions/checkout@v2
      - name: composer install
        run: composer install

      - name: cs-check
        run: composer cs-check

      - name: phpstan
        run: composer phpstan
